# Generated by Django 5.0.2 on 2024-02-17 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('status', models.CharField(max_length=30, verbose_name='Статус')),
                ('server_response', models.TextField(blank='True', null='True', verbose_name='Ответ сервиса')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(verbose_name='Время рассылки')),
                ('frequency', models.CharField(choices=[('Daily', 'Ежедневно'), ('Weekly', 'Еженедельно'), ('Monthly', 'Ежемесячно')], max_length=30, verbose_name='Регулярность')),
                ('status', models.CharField(choices=[('Created', 'Создана'), ('Started', 'Запущена'), ('Completed', 'Завершена')], max_length=30, verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Текст письма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('client', models.ManyToManyField(to='client.client', verbose_name='Клиент')),
                ('mailing_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newletter.mailingsettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
